language: elixir
dist: trusty

elixir:
  - 1.6.6
  - 1.7.2

otp_release:
  - 20.3
  - 21.0

cache:
  directories:
    - _build
    - deps

before_script:
  - MIX_ENV=test mix compile --warnings-as-errors

script:
  - mix test
